### ISSUE TITLE
Error when deploying to Heroic

### ISSUE THREAD

**Issue by oeil2lynx** [superhighfives/list-of-ingredients#1]
Hi, 

I tried to deploy to Heroku after executing these commands : 

heroku apps:create
heroku buildpacks:add heroku/nodejs --index 1
heroku buildpacks:add heroku/ruby --index 2
git push heroku master

Here is the error : 

Counting objects: 149, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (112/112), done.
Writing objects: 100% (149/149), 118.66 KiB | 0 bytes/s, done.
Total 149 (delta 21), reused 149 (delta 21)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote: 
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote: 
remote: -----> Installing binaries
remote:        engines.node (package.json):  6.3.1
remote:        engines.npm (package.json):   unspecified (use default)
remote:        
remote:        Downloading and installing node 6.3.1...
remote:        Using default npm version: 3.10.3
remote: 
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote: 
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:        
remote:        > list-of-ingredients@ postinstall /tmp/build_8019002293b919f270e81da69db417cf
remote:        > npm run build && npm run deploy && echo 'Client built!'
remote:        
remote:        
remote:        > list-of-ingredients@ build /tmp/build_8019002293b919f270e81da69db417cf
remote:        > cd client && npm install && npm run build && cd ..
remote:        
remote:        list-of-ingredients-client@0.1.0 /tmp/build_8019002293b919f270e81da69db417cf/client
remote:        ├─┬ react@15.4.2
remote:        │ ├─┬ fbjs@0.8.11
remote:        │ │ ├── core-js@1.2.7
remote:        │ │ ├─┬ isomorphic-fetch@2.2.1
remote:        │ │ │ ├─┬ node-fetch@1.6.3
remote:        │ │ │ │ ├─┬ encoding@0.1.12
remote:        │ │ │ │ │ └── iconv-lite@0.4.15
remote:        │ │ │ │ └── is-stream@1.1.0
remote:        │ │ │ └── whatwg-fetch@2.0.3
remote:        │ │ ├─┬ promise@7.1.1
remote:        │ │ │ └── asap@2.0.5
remote:        │ │ ├── setimmediate@1.0.5
remote:        │ │ └── ua-parser-js@0.7.12
remote:        │ ├─┬ loose-envify@1.3.1
remote:        │ │ └── js-tokens@3.0.1
remote:        │ └── object-assign@4.1.1
remote:        ├── react-dom@15.4.2
remote:        ├─┬ semantic-ui-css@2.2.9
remote:        │ └── jquery@3.2.1
remote:        └─┬ semantic-ui-react@0.67.2
remote:        ├─┬ babel-runtime@6.23.0
remote:        │ ├── core-js@2.4.1
remote:        │ └── regenerator-runtime@0.10.3
remote:        ├── classnames@2.2.5
remote:        ├─┬ debug@2.6.3
remote:        │ └── ms@0.7.2
remote:        └── lodash@4.17.4
remote:        
remote:        
remote:        > list-of-ingredients-client@0.1.0 build /tmp/build_8019002293b919f270e81da69db417cf/client
remote:        > react-scripts build
remote:        
remote:        sh: 1: react-scripts: not found
remote:        
remote:        npm ERR! Linux 3.13.0-112-generic
remote:        npm ERR! argv "/tmp/build_8019002293b919f270e81da69db417cf/.heroku/node/bin/node" "/tmp/build_8019002293b919f270e81da69db417cf/.heroku/node/bin/npm" "run" "build"
remote:        npm ERR! node v6.3.1
remote:        npm ERR! npm  v3.10.3
remote:        npm ERR! file sh
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno ENOENT
remote:        npm ERR! syscall spawn
remote:        npm ERR! list-of-ingredients-client@0.1.0 build: `react-scripts build`
remote:        npm ERR! spawn ENOENT
remote:        npm ERR!
remote:        npm ERR! Failed at the list-of-ingredients-client@0.1.0 build script 'react-scripts build'.
remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
remote:        npm ERR! If you do, this is most likely a problem with the list-of-ingredients-client package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     react-scripts build
remote:        npm ERR! You can get information on how to open an issue for this project with:
remote:        npm ERR!     npm bugs list-of-ingredients-client
remote:        npm ERR! Or if that isn't available, you can get their info via:
remote:        npm ERR!     npm owner ls list-of-ingredients-client
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_8019002293b919f270e81da69db417cf/client/npm-debug.log
remote:        
remote:        npm ERR! Linux 3.13.0-112-generic
remote:        npm ERR! argv "/tmp/build_8019002293b919f270e81da69db417cf/.heroku/node/bin/node" "/tmp/build_8019002293b919f270e81da69db417cf/.heroku/node/bin/npm" "run" "build"
remote:        npm ERR! node v6.3.1
remote:        npm ERR! npm  v3.10.3
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! list-of-ingredients@ build: `cd client && npm install && npm run build && cd ..`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the list-of-ingredients@ build script 'cd client && npm install && npm run build && cd ..'.
remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
remote:        npm ERR! If you do, this is most likely a problem with the list-of-ingredients package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     cd client && npm install && npm run build && cd ..
remote:        npm ERR! You can get information on how to open an issue for this project with:
remote:        npm ERR!     npm bugs list-of-ingredients
remote:        npm ERR! Or if that isn't available, you can get their info via:
remote:        npm ERR!     npm owner ls list-of-ingredients
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_8019002293b919f270e81da69db417cf/npm-debug.log
remote:        
remote:        npm ERR! Linux 3.13.0-112-generic
remote:        npm ERR! argv "/tmp/build_8019002293b919f270e81da69db417cf/.heroku/node/bin/node" "/tmp/build_8019002293b919f270e81da69db417cf/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_8019002293b919f270e81da69db417cf/.npmrc"
remote:        npm ERR! node v6.3.1
remote:        npm ERR! npm  v3.10.3
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! list-of-ingredients@ postinstall: `npm run build && npm run deploy && echo 'Client built!'`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the list-of-ingredients@ postinstall script 'npm run build && npm run deploy && echo 'Client built!''.
remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
remote:        npm ERR! If you do, this is most likely a problem with the list-of-ingredients package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     npm run build && npm run deploy && echo 'Client built!'
remote:        npm ERR! You can get information on how to open an issue for this project with:
remote:        npm ERR!     npm bugs list-of-ingredients
remote:        npm ERR! Or if that isn't available, you can get their info via:
remote:        npm ERR!     npm owner ls list-of-ingredients
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_8019002293b919f270e81da69db417cf/npm-debug.log
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy....
remote: 
remote: !	Push rejected to damp-plateau-70249.
remote:

**Comment by superhighfives** [comment]
Good pickup! You can either update the `NPM_CONFIG_PRODUCTION` environment variable on Heroku:
```
heroku config:set NPM_CONFIG_PRODUCTION=false
```

(The background on this is covered in **Step 5: Deploy it to Heroku** here: https://medium.com/superhighfives/a-top-shelf-web-stack-rails-5-api-activeadmin-create-react-app-de5481b7ec0b)

Or you can update the `client/package.json` and move `react-scripts` into `dependencies`, which is what I've now updated `master` to: https://github.com/superhighfives/list-of-ingredients/commit/effd009bbcb233734ebc38f503dcca69d1a17a7a
