### ISSUE TITLE
About "Expected to find a manifest file" for anyone reading in 2020 

### ISSUE THREAD

**Issue by JohnFajardo** [superhighfives/list-of-ingredients#21]
You just need and empty manifest.js file in your `/app/assets/config` folder:

```
 mkdir -p app/assets/config && echo '{}' > app/assets/config/manifest.js
```

**Comment by JohnFajardo** [comment]
Closing right away, just wanted to leave for reference.

**Comment by superhighfives** [comment]
Thanks @ThatJohn—the latest version of this repo is available at https://github.com/heroku/list-of-ingredients, which is a more up to date and better documented repo ([and related tutorial](https://blog.heroku.com/a-rock-solid-modern-web-stack)).

Appreciate you opening the issue!
