### ISSUE TITLE
Client routes with React Router

### ISSUE THREAD

**Issue by codingInSpace** [superhighfives/list-of-ingredients#4]
I didn't bootstrap my client with create-react-app, but I think it's the same case. If not, please inform me if you have client routing working.

Putting the index.html with the bundled client in the rails public folder works for loading the SPA on '/' and interacting with it, but not when reloading the page after navigating to different routes in the client. Hitting an url that is a client route does nothing when the server looks for api routes.  

With a node server you usually solve this by having a catch all route that serves the index file for any routes that aren't api routes, and React Router then intercepts. Excluding server rendering:

```javascript
app.get('*', (req, res) => {
    res.sendFile(path.resolve(__dirname, '..', 'public', 'index.html'))
})
```

Since I'd prefer not to have two separate servers for the api and the frontend (small scale project) I've tried a few ways to do the same for this approach with a simple Rails api.

---

```ruby
# config/routes.db
scope '/api' do
    #something
end

root '/'
get '*path', to: '/'
```   
Above just hits the root url for any unmatched (by api) route, React Router does not intercept.  

---

```ruby
# config/routes.db
scope '/api' do
    #something
end
root 'something#index'
get '*path', to: 'something#index'
```
   
```ruby
# app/controllers/something_controller.rb
class SomethingController < ApplicationController
    def index
	render :file => 'public/index.html'
    end
end
```
Above gives blank page for anything else than root url.  

Same if I try @location_path = "/#{params[:path]}" instead of rendering index file.  

Any ideas that could help? At this point I can't figure out a way to use this whole approach together with client routing. Maybe there is no way to achieve this without using the view layer engine of Rails?

Thanks in advance.

**Comment by superhighfives** [comment]
I recently answered this question following some research @geelen did:
https://medium.com/@superhighfives/hey-logan-d73126d71271

It's a little more prescriptive in the routing, and puts the fallback at the app level, but otherwise looks pretty similar to your setup—let me know if it helps.

**Comment by codingInSpace** [comment]
Thanks a lot for getting back to me, I solved it.

Except for the constraints it did do the same as the second example I had (blank page), but knowing that it worked for <i>someone</i> pushed me to realize that maybe ActionController::API doesn't do rendering files the same way ActionController::Base does :man_facepalming: It's always RTFM I guess

So thanks for helping me learn a bit more about Rails and thank you for the original article!

**Comment by superhighfives** [comment]
Ah, yep! It's one of the stipulations for handling the ActiveAdmin views, too. Glad you figured it out, and thanks for your kind words!
