### ISSUE TITLE
I ran into a small assets issue

### ISSUE THREAD

**Issue by baash05** [superhighfives/list-of-ingredients#7]
I ran into this issue. 
https://github.com/shakacode/react_on_rails/issues/430
The bit at the end fixed it. 

I also noticed you didn't have rake db:create

PS. thanks so much!

**Comment by superhighfives** [comment]
Hey @baash05—thanks for the feedback!

It'd be great to better understand the issue you ran into. Were you using React on Rails with this project? Also, where did you run into the issue with `rake db:create`? Are you using sqlite locally, or postgres?

Thanks!

**Comment by superhighfives** [comment]
Also, there's a newer version of this tutorial here for Rails 5.2.0: https://blog.heroku.com/a-rock-solid-modern-web-stack

**Comment by baash05** [comment]
Ah.. using pg locally.


------------------------------------------------
You know that I write slowly. This is chiefly because I am never satisfied
until I have said as much as possible in a few words, and writing briefly
takes far more time than writing at length.
— Karl Friedrich Gauss
-----------------------------------------------

**Comment by superhighfives** [comment]
Yeah, that will be the cause—thanks for flagging! I’ll make sure I add a reference to that in the post.l
